export const defaultUrl = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

export const mockTranscriptData = {
  language: "ENGLISH",
  duration: 0,
  segments: [
    {
      id: 0,
      seek: 0,
      start: 0,
      end: 18.8,
      text: "[Music]",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 1,
      seek: 0,
      start: 18.8,
      end: 21.8,
      text: "we&#39;re no strangers to",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 2,
      seek: 0,
      start: 21.8,
      end: 26.039,
      text: "love you know the rules and so do",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 3,
      seek: 0,
      start: 26.039,
      end: 29.64,
      text: "I I full commitments while I&#39;m thinking",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 4,
      seek: 0,
      start: 29.64,
      end: 31.24,
      text: "of",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 5,
      seek: 0,
      start: 31.24,
      end: 35.52,
      text: "you wouldn&#39;t get this from any other guy",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 6,
      seek: 0,
      start: 35.52,
      end: 39.44,
      text: "I just want to tell you how I&#39;m",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 7,
      seek: 0,
      start: 39.44,
      end: 43.36,
      text: "feeling got to make you understand Never",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 8,
      seek: 0,
      start: 43.36,
      end: 46.199,
      text: "Going To Give You Up never going to let",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 9,
      seek: 0,
      start: 46.199,
      end: 49.719,
      text: "you down never going to run around and",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 10,
      seek: 0,
      start: 49.719,
      end: 53.64,
      text: "desert you never going to make you cry",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 11,
      seek: 0,
      start: 53.64,
      end: 56.12,
      text: "never going to say goodbye never going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 12,
      seek: 0,
      start: 56.12,
      end: 60.76,
      text: "to tell a lie and hurt you",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 13,
      seek: 0,
      start: 60.76,
      end: 63.96,
      text: "we&#39;ve known each other for so",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 14,
      seek: 0,
      start: 63.96,
      end: 67.32,
      text: "long your heart&#39;s been aching but your",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 15,
      seek: 0,
      start: 67.32,
      end: 70.6,
      text: "to sh to say it inside we both know",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 16,
      seek: 0,
      start: 70.6,
      end: 72.52,
      text: "what&#39;s been going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 17,
      seek: 0,
      start: 72.52,
      end: 76.64,
      text: "on we know the game and we&#39;re going to",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 18,
      seek: 0,
      start: 76.64,
      end: 81.4,
      text: "playing and if you ask me how I&#39;m",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 19,
      seek: 0,
      start: 81.4,
      end: 84.6,
      text: "feeling don&#39;t tell me you&#39;re too my you",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 20,
      seek: 0,
      start: 84.6,
      end: 87.72,
      text: "see Never Going To Give You Up never",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 21,
      seek: 0,
      start: 87.72,
      end: 90.799,
      text: "going to let you down never to run",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 22,
      seek: 0,
      start: 90.799,
      end: 94.399,
      text: "around and desert you never going to",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 23,
      seek: 0,
      start: 94.399,
      end: 98.079,
      text: "make you cry never going to say goodbye",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 24,
      seek: 0,
      start: 98.079,
      end: 102.24,
      text: "never going to tell a lie and hurt you",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 25,
      seek: 0,
      start: 102.24,
      end: 104.68,
      text: "never going to give you up never going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 26,
      seek: 0,
      start: 104.68,
      end: 107.68,
      text: "to let you down never going to run",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 27,
      seek: 0,
      start: 107.68,
      end: 111.32,
      text: "around and desert you never going to",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 28,
      seek: 0,
      start: 111.32,
      end: 115.2,
      text: "make you cry never going to sing goodbye",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 29,
      seek: 0,
      start: 115.2,
      end: 118.84,
      text: "going to tell a lie and hurt",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 30,
      seek: 0,
      start: 118.84,
      end: 121.96,
      text: "you",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 31,
      seek: 0,
      start: 121.96,
      end: 125.24,
      text: "give",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 32,
      seek: 0,
      start: 125.24,
      end: 127.64,
      text: "you give",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 33,
      seek: 0,
      start: 127.64,
      end: 131.879,
      text: "you going to give going to give",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 34,
      seek: 0,
      start: 131.879,
      end: 135.84,
      text: "you going to give going to give",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 35,
      seek: 0,
      start: 135.84,
      end: 140.04,
      text: "you we&#39;ve known each other for so",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 36,
      seek: 0,
      start: 140.04,
      end: 143.36,
      text: "long your heart&#39;s been aching but you&#39;re",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 37,
      seek: 0,
      start: 143.36,
      end: 146.92,
      text: "too sh to say inside we both know what&#39;s",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 38,
      seek: 0,
      start: 146.92,
      end: 148.48,
      text: "been going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 39,
      seek: 0,
      start: 148.48,
      end: 152.72,
      text: "on we the game and we&#39;re going to play",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 40,
      seek: 0,
      start: 152.72,
      end: 157.76,
      text: "it I just want to tell you how I&#39;m",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 41,
      seek: 0,
      start: 157.76,
      end: 161.64,
      text: "feeling got to make you understand Never",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 42,
      seek: 0,
      start: 161.64,
      end: 164.48,
      text: "Going To Give You Up never going to let",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 43,
      seek: 0,
      start: 164.48,
      end: 168.08,
      text: "you down never going to run around and",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 44,
      seek: 0,
      start: 168.08,
      end: 171.959,
      text: "desert you never going to make you cry",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 45,
      seek: 0,
      start: 171.959,
      end: 174.44,
      text: "never going to say goodbye never going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 46,
      seek: 0,
      start: 174.44,
      end: 178.64,
      text: "to tell you my and Hurt You Never Going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 47,
      seek: 0,
      start: 178.64,
      end: 180.4,
      text: "To Give You Up",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 48,
      seek: 0,
      start: 180.4,
      end: 182.879,
      text: "never going to let you down never going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 49,
      seek: 0,
      start: 182.879,
      end: 187.08,
      text: "to run around and desert you never going",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 50,
      seek: 0,
      start: 187.08,
      end: 191.04,
      text: "to make you C never going to say goodbye",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 51,
      seek: 0,
      start: 191.04,
      end: 192.4,
      text: "never going to",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 52,
      seek: 0,
      start: 192.4,
      end: 196.64,
      text: "tell and Hur You Never Going To Give You",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 53,
      seek: 0,
      start: 196.64,
      end: 199.68,
      text: "Up never going to let you down never",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 54,
      seek: 0,
      start: 199.68,
      end: 203.959,
      text: "going to run around and desert you never",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 55,
      seek: 0,
      start: 203.959,
      end: 207.03,
      text: "going to make you going to",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 56,
      seek: 0,
      start: 207.03,
      end: 208.68,
      text: "[Music]",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 57,
      seek: 0,
      start: 208.68,
      end: 211,
      text: "goodbye",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
    {
      id: 58,
      seek: 0,
      start: 211,
      end: 214,
      text: "and",
      tokens: null,
      temperature: 0,
      avg_logprob: 0,
      compression_ratio: 0,
      no_speech_prob: 0,
      transient: false,
    },
  ],
  info: {
    title: "Rick Astley - Never Gonna Give You Up (Official Music Video) - YouTube",
    description:
      "The official video for “Never Gonna Give You Up” by Rick Astley. Never: The Autobiography 📚 OUT NOW! Follow this link to get your copy and listen to Rick’s ...",
    channelName: "Rick Astley",
    duration: 212.091,
    defaultAudioLanguage: "",
  },
  text: "[Music] we&#39;re no strangers to love you know the rules and so do I I full commitments while I&#39;m thinking of you wouldn&#39;t get this from any other guy I just want to tell you how I&#39;m feeling got to make you understand Never Going To Give You Up never going to let you down never going to run around and desert you never going to make you cry never going to say goodbye never going to tell a lie and hurt you we&#39;ve known each other for so long your heart&#39;s been aching but your to sh to say it inside we both know what&#39;s been going on we know the game and we&#39;re going to playing and if you ask me how I&#39;m feeling don&#39;t tell me you&#39;re too my you see Never Going To Give You Up never going to let you down never to run around and desert you never going to make you cry never going to say goodbye never going to tell a lie and hurt you never going to give you up never going to let you down never going to run around and desert you never going to make you cry never going to sing goodbye going to tell a lie and hurt you give you give you going to give going to give you going to give going to give you we&#39;ve known each other for so long your heart&#39;s been aching but you&#39;re too sh to say inside we both know what&#39;s been going on we the game and we&#39;re going to play it I just want to tell you how I&#39;m feeling got to make you understand Never Going To Give You Up never going to let you down never going to run around and desert you never going to make you cry never going to say goodbye never going to tell you my and Hurt You Never Going To Give You Up never going to let you down never going to run around and desert you never going to make you C never going to say goodbye never going to tell and Hur You Never Going To Give You Up never going to let you down never going to run around and desert you never going to make you going to [Music] goodbye and ",
};
